wallpaper {
    monitor = DP-1
    path = /home/lolleo/Pictures/Wallpapers/pexels-nathanmarcam-10558778.jpg
    fit_mode = cover
}
wallpaper {
    monitor = 
    path = /home/lolleo/Pictures/Wallpapers/japan-artistic-5120x2880-25406.jpg
    fit_mode = cover
}
splash = false
ipc = true