# ============================================================
# Font
# ============================================================

font_family Consolas
font_size 12.0


# ============================================================
# Window
# ============================================================

window_padding_width 12
hide_window_decorations yes
confirm_os_window_close 0


# ============================================================
# Cursor
# ============================================================

cursor_shape beam

cursor            #ABB2BF
cursor_text_color #282C34


# ============================================================
# Scrollback
# ============================================================

scrollback_lines 10000


# ============================================================
# Behavior
# ============================================================

enable_audio_bell no

shell /bin/zsh


# ============================================================
# Colors
# ============================================================

foreground            #ABB2BF
background	      #111318

selection_foreground  #282C34
selection_background  #ABB2BF

url_color             #61AFEF


# ============================================================
# ANSI Colors (One Dark)
# ============================================================

# Black
color0  #282C34
color8  #5C6370

# Red
color1  #E06C75
color9  #E06C75

# Green
color2  #98C379
color10 #98C379

# Yellow
color3  #E5C07B
color11 #E5C07B

# Blue
color4  #61AFEF
color12 #61AFEF

# Magenta
color5  #C678DD
color13 #C678DD

# Cyan
color6  #56B6C2
color14 #56B6C2

# White
color7  #ABB2BF
color15 #FFFFFF
